#!/usr/bin/env bash
# Snapshot the Claude Code Pro/Max OAuth token from the macOS Keychain
# into .env.claude, so the claude-subscription Docker stack
# (docker-compose.claude.yml) can authenticate headless `claude --print`
# without API credits.
#
# The token is short-lived (~hours). The host `claude` CLI refreshes it
# in the Keychain automatically; this script just copies the CURRENT
# value out. Re-run before `make claude-up` whenever LLM calls start
# failing with an auth error.
#
# Usage: scripts/claude-token.sh   (or: make claude-token)
set -euo pipefail

ENV_FILE=".env.claude"

if [[ "$(uname)" != "Darwin" ]]; then
  echo "✗ This helper reads the macOS Keychain; on Linux export"
  echo "  CLAUDE_CODE_OAUTH_TOKEN yourself (run 'claude setup-token')."
  exit 1
fi

# Force the host CLI to refresh the Keychain token before we read it.
# The OAuth token in the Keychain only rotates when `claude` actually
# makes a call; without this nudge a stale/expired token gets copied
# and every container LLM call 401s. A trivial --print ping is enough.
if command -v claude >/dev/null 2>&1; then
  echo "Refreshing host session token…"
  echo "ping" | claude --print --model sonnet >/dev/null 2>&1 || true
fi

RAW="$(security find-generic-password -s 'Claude Code-credentials' -w 2>/dev/null || true)"
if [[ -z "$RAW" ]]; then
  echo "✗ No 'Claude Code-credentials' entry in the Keychain."
  echo "  Log in with the desktop Claude Code CLI first ('claude' then /login)."
  exit 1
fi

TOKEN="$(printf '%s' "$RAW" | python3 -c \
  'import sys,json; print(json.load(sys.stdin)["claudeAiOauth"]["accessToken"])' 2>/dev/null || true)"
if [[ -z "$TOKEN" || "${TOKEN:0:11}" != "sk-ant-oat0" ]]; then
  echo "✗ Could not parse an OAuth access token from the Keychain entry."
  exit 1
fi

EXPIRES="$(printf '%s' "$RAW" | python3 -c \
  'import sys,json,datetime; e=json.load(sys.stdin)["claudeAiOauth"].get("expiresAt"); print(datetime.datetime.fromtimestamp(e/1000).isoformat() if e else "unknown")' 2>/dev/null || echo unknown)"

# Write .env.claude — static stack config + the volatile token. This
# file is gitignored (.env.*). Overwritten on every run.
cat > "$ENV_FILE" <<EOF
# Generated by scripts/claude-token.sh — DO NOT COMMIT.
# Pro/Max OAuth token snapshot (expires: ${EXPIRES}).
# Re-run 'make claude-token' to refresh, then 'make claude-up'.
CLAUDE_CODE_OAUTH_TOKEN=${TOKEN}

# --- claude-subscription stack config (safe to edit) ---
CLAUDE_FRONTEND_PORT=3100
CLAUDE_BACKEND_PORT=8100
CLAUDE_NEXT_PUBLIC_API_URL=http://localhost:8100
CLAUDE_CORS_ORIGINS=http://localhost:3100
CLAUDE_STACK_MODEL=opus
CLAUDE_LLM_TIMEOUT_SECONDS=600
EOF
chmod 600 "$ENV_FILE"

# Also write the LIVE token file the running container reads on every
# call (CLAUDE_OAUTH_TOKEN_FILE → ~/.applyagent/claude_token, mounted
# read-only into the backend). Writing this lets the hourly watcher
# refresh the token with NO container restart. Atomic write (temp +
# mv) so a call never reads a half-written file.
LIVE_DIR="${HOME}/.applyagent"
mkdir -p "$LIVE_DIR"
printf '%s' "$TOKEN" > "${LIVE_DIR}/claude_token.tmp"
chmod 600 "${LIVE_DIR}/claude_token.tmp"
mv -f "${LIVE_DIR}/claude_token.tmp" "${LIVE_DIR}/claude_token"

echo "✓ Wrote ${ENV_FILE} + ${LIVE_DIR}/claude_token"
echo "  token: ${TOKEN:0:14}… (len ${#TOKEN})"
echo "  expires: ${EXPIRES}"
echo "  next: make claude-up"
